CREATE OR REPLACE PACKAGE PKG_DYNAMIC_PARSER AS
  -- Global collection type for tokens
  g_tokens         lexer_token_col;
  g_curr_token_ix  NUMBER := 1;

  PROCEDURE pr_assignment_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_block(po_success OUT BOOLEAN);
  PROCEDURE pr_block_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_block_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_collection_type_definition(po_success OUT BOOLEAN);
  PROCEDURE pr_collection_type_definition_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_column_list(po_success OUT BOOLEAN);
  PROCEDURE pr_column_list_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_commit_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_condition(po_success OUT BOOLEAN);
  PROCEDURE pr_constant_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_cursor_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_cursor_declaration_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_data_type(po_success OUT BOOLEAN);
  PROCEDURE pr_data_type_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_declaration_section(po_success OUT BOOLEAN);
  PROCEDURE pr_declaration_section_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_dynamic_sql_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_dynamic_sql_statement_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_exception_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_exception_handler(po_success OUT BOOLEAN);
  PROCEDURE pr_exception_name(po_success OUT BOOLEAN);
  PROCEDURE pr_exception_section(po_success OUT BOOLEAN);
  PROCEDURE pr_exception_section_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_executable_section(po_success OUT BOOLEAN);
  PROCEDURE pr_executable_section_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_exit_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_exit_statement_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_expression(po_success OUT BOOLEAN);
  PROCEDURE pr_expression_list(po_success OUT BOOLEAN);
  PROCEDURE pr_expression_list_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_expression_tail(po_success OUT BOOLEAN);
  PROCEDURE pr_field_name(po_success OUT BOOLEAN);
  PROCEDURE pr_for_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_function_body(po_success OUT BOOLEAN);
  PROCEDURE pr_function_body_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_function_call(po_success OUT BOOLEAN);
  PROCEDURE pr_function_call_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_function_spec(po_success OUT BOOLEAN);
  PROCEDURE pr_function_spec_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_if_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_index_by_type(po_success OUT BOOLEAN);
  PROCEDURE pr_literal(po_success OUT BOOLEAN);
  PROCEDURE pr_loop_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_null_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_operator(po_success OUT BOOLEAN);
  PROCEDURE pr_other_sql_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_package_body(po_success OUT BOOLEAN);
  PROCEDURE pr_package_body_element(po_success OUT BOOLEAN);
  PROCEDURE pr_package_body_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_package_element(po_success OUT BOOLEAN);
  PROCEDURE pr_package_spec(po_success OUT BOOLEAN);
  PROCEDURE pr_package_spec_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_parameter_list(po_success OUT BOOLEAN);
  PROCEDURE pr_parameter_list_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_parameter_spec(po_success OUT BOOLEAN);
  PROCEDURE pr_parameter_spec_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_parameter_spec_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_body(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_body_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_call(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_call_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_spec(po_success OUT BOOLEAN);
  PROCEDURE pr_procedure_spec_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_raise_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_raise_statement_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_range(po_success OUT BOOLEAN);
  PROCEDURE pr_record_field_spec(po_success OUT BOOLEAN);
  PROCEDURE pr_record_field_spec_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_record_field_spec_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_record_type_definition(po_success OUT BOOLEAN);
  PROCEDURE pr_record_type_definition_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_ref_cursor_type_definition(po_success OUT BOOLEAN);
  PROCEDURE pr_ref_cursor_type_definition_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_rollback_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_statement(po_success OUT BOOLEAN);
  PROCEDURE pr_table_or_view_reference(po_success OUT BOOLEAN);
  PROCEDURE pr_table_or_view_reference_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_term(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_body(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_body_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_event(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_event_list(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_event_list_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_time_event(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_time_event_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_time_event_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_timing(po_success OUT BOOLEAN);
  PROCEDURE pr_trigger_when_clause(po_success OUT BOOLEAN);
  PROCEDURE pr_type_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_type_definition(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_declaration(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_declaration_opt_1(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_declaration_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_reference(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_reference_opt_2(po_success OUT BOOLEAN);
  PROCEDURE pr_variable_reference_rep_1(po_success OUT BOOLEAN);
  PROCEDURE pr_while_statement(po_success OUT BOOLEAN);

  -- Main entry point for top-level parsing rules
  PROCEDURE pr_increment_token_ix;
  PROCEDURE parse_main(p_token_stream IN lexer_token_col, po_success OUT BOOLEAN);
END PKG_DYNAMIC_PARSER;
/


